from app.models import Scenario


SCENARIOS: list[Scenario] = [
    Scenario(
        id="seoul-live-default",
        name="강남에서 종로까지 통합 판단",
        city="서울",
        route_name="2호선 강남역 탑승 후 3호선 안국역 하차",
        target_stop_name="종로1가 공평도시유적전시관 접근",
        primary_mode_label="지하철",
        walk_distance_m=780,
        signal_wait_sec=34,
        crossing_distance_m=22,
        crossing_window_sec=13,
        bus_remaining_distance_m=2400,
        bus_speed_kph=27.0,
        bus_reliability=0.72,
        bus_freshness_sec=15,
        congestion_level=0.68,
        is_last_bus=False,
        is_night=False,
        alternative_label="을지로입구역 하차 후 종로권 진입",
        alternative_eta_sec=840,
        note="강남역 출구 접근과 안국역 하차 후 종로권 진입 보행이 함께 살아 있는 대표 시연 경로",
    ),
    Scenario(
        id="jamsil-to-coex",
        name="잠실역에서 코엑스까지 이동 판단",
        city="서울",
        route_name="2호선 잠실역 탑승 후 삼성역 하차",
        target_stop_name="코엑스 동문 접근",
        primary_mode_label="지하철",
        walk_distance_m=720,
        signal_wait_sec=30,
        crossing_distance_m=20,
        crossing_window_sec=14,
        bus_remaining_distance_m=1900,
        bus_speed_kph=25.0,
        bus_reliability=0.74,
        bus_freshness_sec=14,
        congestion_level=0.61,
        is_last_bus=False,
        is_night=False,
        alternative_label="봉은사역 방향 대안 동선",
        alternative_eta_sec=660,
        note="잠실역 출구 접근과 삼성역 하차 후 코엑스 동문까지의 긴 도보 구간을 함께 보는 대표 시나리오",
    ),
    Scenario(
        id="hongdae-to-deoksugung",
        name="홍대입구역에서 덕수궁까지 이동 판단",
        city="서울",
        route_name="2호선 홍대입구역 탑승 후 시청역 하차",
        target_stop_name="덕수궁 돌담길 북단 접근",
        primary_mode_label="지하철",
        walk_distance_m=790,
        signal_wait_sec=28,
        crossing_distance_m=19,
        crossing_window_sec=15,
        bus_remaining_distance_m=3150,
        bus_speed_kph=31.0,
        bus_reliability=0.71,
        bus_freshness_sec=16,
        congestion_level=0.66,
        is_last_bus=False,
        is_night=False,
        alternative_label="시청역 10번 출구 대안 동선",
        alternative_eta_sec=780,
        note="홍대입구역 접근과 시청역 하차 후 덕수궁 방면 보행을 함께 반영하는 도심형 시나리오",
    ),
    Scenario(
        id="yeouido-to-gwanghwamun",
        name="여의도역에서 광화문광장까지 이동 판단",
        city="서울",
        route_name="5호선 여의도역 탑승 후 광화문역 하차",
        target_stop_name="광화문광장 북측 접근",
        primary_mode_label="지하철",
        walk_distance_m=760,
        signal_wait_sec=32,
        crossing_distance_m=24,
        crossing_window_sec=14,
        bus_remaining_distance_m=2300,
        bus_speed_kph=26.0,
        bus_reliability=0.75,
        bus_freshness_sec=14,
        congestion_level=0.64,
        is_last_bus=False,
        is_night=False,
        alternative_label="시청역 하차 후 세종대로 진입",
        alternative_eta_sec=900,
        note="여의도 업무권에서 광화문광장까지 이동할 때 출발 전 보행과 광화문역 하차 후 마지막 접근을 함께 보는 시나리오",
    ),
    Scenario(
        id="sadang-to-seoul-station",
        name="사당역에서 서울역까지 이동 판단",
        city="서울",
        route_name="4호선 사당역 탑승 후 서울역 하차",
        target_stop_name="서울역 서부역 접근",
        primary_mode_label="지하철",
        walk_distance_m=740,
        signal_wait_sec=29,
        crossing_distance_m=18,
        crossing_window_sec=12,
        bus_remaining_distance_m=2600,
        bus_speed_kph=28.0,
        bus_reliability=0.73,
        bus_freshness_sec=15,
        congestion_level=0.59,
        is_last_bus=False,
        is_night=False,
        alternative_label="회현역 하차 후 남대문로 진입",
        alternative_eta_sec=870,
        note="사당역 출구 접근과 서울역 서부역 진입 사이를 안정적으로 맞추는 장거리 출퇴근형 시나리오",
    ),
    Scenario(
        id="seongsu-to-sports-complex",
        name="성수역에서 잠실종합운동장까지 이동 판단",
        city="서울",
        route_name="2호선 성수역 탑승 후 종합운동장역 하차",
        target_stop_name="잠실종합운동장 주경기장 접근",
        primary_mode_label="지하철",
        walk_distance_m=830,
        signal_wait_sec=31,
        crossing_distance_m=21,
        crossing_window_sec=14,
        bus_remaining_distance_m=2800,
        bus_speed_kph=29.0,
        bus_reliability=0.70,
        bus_freshness_sec=13,
        congestion_level=0.67,
        is_last_bus=False,
        is_night=False,
        alternative_label="잠실새내역 하차 후 대안 동선",
        alternative_eta_sec=960,
        note="성수동에서 잠실종합운동장까지 이동할 때 긴 탑승 구간과 경기장 접근 도보를 함께 보여주는 시나리오",
    ),
]
